-- ========================================================
-- 플래너 전용 Supabase 추가 테이블 DDL (supabase_planner_addon.sql)
-- 주의: 기존 'lessons' 및 'test_records' 테이블은 이미 존재하므로
--       본 스크립트는 플래너 구동에 필요한 신규 테이블만 추가 생성합니다.
-- ========================================================

-- 1. 과목 메타정보 테이블 (과목명 기준)
CREATE TABLE IF NOT EXISTS subjects (
    name TEXT PRIMARY KEY,
    dday TEXT,
    target_score INTEGER DEFAULT 100,
    color TEXT DEFAULT 'indigo',
    academy_name TEXT DEFAULT '',
    chapters JSONB DEFAULT '[]'::jsonb,
    mock_tests JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 기존 subjects 테이블에 컬럼이 없는 경우 마이그레이션 구문
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS academy_name TEXT DEFAULT '';
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS chapters JSONB DEFAULT '[]'::jsonb;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS mock_tests JSONB DEFAULT '[]'::jsonb;

-- 2. 현재 활성 일정 관리 테이블 (lessons 공유 테이블 연동)
CREATE TABLE IF NOT EXISTS schedules (
    id TEXT PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    date TEXT NOT NULL,
    category TEXT DEFAULT '진도계획',
    title TEXT NOT NULL,
    detail TEXT DEFAULT '',
    progress INTEGER DEFAULT 0,
    score TEXT DEFAULT '',
    duration_sec INTEGER DEFAULT 0,
    completed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 플래너 전역 설정
CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 시험 마감 종합 통계 아카이브 메타데이터
CREATE TABLE IF NOT EXISTS exam_archives (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,                        -- 시험명 (예: 1학기 중간고사)
    start_date TEXT,                             -- 대비 시작일
    dday TEXT,                                   -- 시험 D-Day
    actual_avg_score NUMERIC,                    -- 최종 시험 평균점수
    final_scores_text TEXT,                      -- 성적 텍스트 (예: '영어 95점, 국어 92점')
    total_duration_sec INTEGER DEFAULT 0,        -- 총 누적 학습시간(초)
    category_times JSONB DEFAULT '{}'::jsonb,    -- 카테고리별 시간 (학원, 자습, 진도 등)
    weekly_pace JSONB DEFAULT '{}'::jsonb,       -- 주차별 공부시간 추이 (D-4w ~ D-Day)
    summary JSONB DEFAULT '{}'::jsonb,           -- 기타 종합 코멘트
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 과목별 아카이브 통계 (영구 보존 - 원본 테이블과 독립)
CREATE TABLE IF NOT EXISTS archive_subject_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id TEXT NOT NULL REFERENCES exam_archives(id) ON DELETE CASCADE,
    subject_name TEXT NOT NULL,
    target_score INTEGER DEFAULT 100,
    final_score NUMERIC,                         -- 마지막 실제 시험 결과 점수 (지필고사)
    total_duration_sec INTEGER DEFAULT 0,        -- 과목별 총 누적 학습시간
    acad_duration_sec INTEGER DEFAULT 0,         -- 학원 시간
    self_duration_sec INTEGER DEFAULT 0          -- 자습 시간
);

-- 6. 단원별 아카이브 통계 (영구 보존: 회차별 점수 추이 score_trend 보관)
-- 주의: lessons(id) 외래키를 걸지 않고 unit_name을 독립 보관하여
--       시험 마감 시 lessons를 DELETE해도 아카이브 통계가 100% 안전하게 유지됩니다.
CREATE TABLE IF NOT EXISTS archive_lesson_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id TEXT NOT NULL REFERENCES exam_archives(id) ON DELETE CASCADE,
    subject_name TEXT NOT NULL,
    unit_name TEXT NOT NULL,
    study_duration_sec INTEGER DEFAULT 0,        -- 단원별 총 학습시간
    avg_score NUMERIC,                           -- 단원 전체 테스트 평균점수
    score_trend JSONB DEFAULT '[]'::jsonb,       -- 회차별 성적 추이: [{"round":1, "score":70}, {"round":2, "score":85}...]
    category_scores JSONB DEFAULT '{}'::jsonb,   -- 카테고리별 평균점수 (VOCAB, UNIT, WRITING 등)
    test_count INTEGER DEFAULT 0                 -- 총 응시 횟수
);

-- 7. Row Level Security (RLS) 활성화 및 공용 접근 정책
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_subject_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_lesson_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon for subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon for schedules" ON schedules FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon for app_settings" ON app_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon for exam_archives" ON exam_archives FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon for archive_subject_stats" ON archive_subject_stats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon for archive_lesson_stats" ON archive_lesson_stats FOR ALL USING (true) WITH CHECK (true);
